### ISSUE TITLE
Main branch frozen for upstream update | branch:main

### ISSUE THREAD

**Issue by dtfranz** [openshift/operator-framework-operator-controller#30]
/label tide/merge-blocker

**Comment by ncdc** [comment]
@dtfranz I added the label for you

**Comment by dtfranz** [comment]
> @dtfranz I added the label for you

Thanks @ncdc, seems I don't have permissions to label issues

**Comment by ncdc** [comment]
Honestly, if we coordinate, we can probably forego this. It's not like there are any other open PRs in here currently 😄

**Comment by dtfranz** [comment]
> Honestly, if we coordinate, we can probably forego this. It's not like there are any other open PRs in here currently 😄

Haha yeah I figured that too. At least this time I'll do the process all the way through just to get used to it :)
